# Generated by Django 2.2.2 on 2019-08-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_auto_20190827_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='name',
            new_name='restaurant_name',
        ),
    ]
