# Generated by Django 2.2.2 on 2019-08-27 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_auto_20190827_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='restaurant_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restapp.Restaurants'),
        ),
    ]
